"""revmove total_pages from books

Revision ID: 325788744612
Revises: 83c51dbaf086
Create Date: 2026-05-04 13:18:28.950861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325788744612'
down_revision: Union[str, Sequence[str], None] = '83c51dbaf086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'total_pages')
    op.add_column('reviews', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('reviews', 'body')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('reviews', 'content')
    op.add_column('books', sa.Column('total_pages', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
